# IP Addressses of Github

name: public-ip

# Controls when the workflow will run
on:
#   schedule:
#     - cron: '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: dearbot/github-public-ip
          token: ${{ secrets.PAT }}
          ref: main
          path: data
          # lfs: true
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python public.py
      - name: ip
        id: ip
        uses: haythem/public-ip@v1.2
      - run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      - name: push to repo
        continue-on-error: true
        run: |
          cd data
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # git lfs install
          # git lfs track "microsoft/*.json"
          # git add .gitattributes
          git add .
          git commit -m "commit 🚀🚀🚀" -a
          git push

