# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: dearbot/max-number-of-files
        token: ${{ secrets.PAT }}
        ref: main
        path: data
        lfs: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: check for changes and git push
      run: |
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER
        cd data
        git branch --show-current
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git rm data/data
        # git add .
        git commit -m "Add changes"
        git push
       
