# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: user_V1

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
    inputs:
      timeout:
        description: 'timeout for minutes'     
        default: "1"
        
jobs:
  build:
    runs-on: ubuntu-latest
    #timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: dearbot/github-user
        token: ${{ secrets.PAT }}
        ref: main
        path: data
        lfs: true
    - uses: actions/cache@v2
      with:
        path: |
          ./relations
        key: cache-relations-${{ github.run_number }} 
        restore-keys: |
            cache-relations-
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: python user_v4.py ${{ secrets.PAT }} ${{ github.event.inputs.timeout }}
      if: github.event_name == 'workflow_dispatch'
    - run: python user_v4.py ${{ secrets.PAT }} 120
      if: github.event_name == 'schedule'
    - run: |
        python user_v4.py
        cat data/README.md
        tar zcvf users.tgz ./data/jobs/*
      name: output
#     - name: check for changes and git push
#       continue-on-error: true
#       run: |
#         cd data
#         git branch --show-current
#         if [[ `git status -s` ]]; then
#           echo "CHANGED"
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git add jobs/$GITHUB_RUN_NUMBER
#           git add README.md
#           git commit -m "Add changes" -a
#           git push
#         else
#           echo "NO CHANGED"
#         fi
    - uses: actions/upload-artifact@v2
      with:
        name: relations
        path: ./relations
    - name: B2 Upload
      uses: wilsonzlin/b2-upload-action@v1.0.1
      with:
        bucket: github-user
        uploadKey: users.tgz
        keyId: ${{ sercets.B2ID }}
        applicationKey: ${{ sercets.B2KEY }}
        file: ./users.tgz
        contentType: b2/x-auto
    - name: B2 Upload
      uses: wilsonzlin/b2-upload-action@v1.0.1
      with:
        bucket: github-user
        uploadKey: ${{ github.run_number }}_README.md
        keyId: ${{ sercets.B2ID }}
        applicationKey: ${{ sercets.B2KEY }}
        file: ./data/README.md
        contentType: b2/x-auto
