# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: user_V1

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
    inputs:
      timeout:
        description: 'timeout for minutes'     
        default: "1"
        
jobs:
  build:
    runs-on: ubuntu-latest
    #timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: dearbot/github-user
        token: ${{ secrets.PAT }}
        ref: main
        path: git
    - name: Download file from Backblaze B2
      # You may pin to the exact commit or the version.
      # uses: sksat/b2-download-action@34b675c16a70d8f08d92241d4e459e687a35c594
      uses: sksat/b2-download-action@v0.1.0
      with:
        key_id: ${{ secrets.B2ID }}
        key: ${{ secrets.B2KEY }}
        bucket: github-user
        file_name: users.tgz
        local_name: users.tgz
    - run: tar zxvf users.tgz -C .
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: python user_v4.py ${{ secrets.PAT }} ${{ github.event.inputs.timeout }}
      if: github.event_name == 'workflow_dispatch'
    - run: python user_v4.py ${{ secrets.PAT }} 45
      if: github.event_name == 'schedule'
    - run: |
        # make output
        python user_v4.py
        cat data/README.md
        
        # make b2 backup
        tar zcvf users.tgz ./data/jobs/* ./relations/*
        
        # make git backup
        cp ./data/README.md ./git/README.md
        cp ./data/README.md ./git/${GITHUB_RUN_NUMBER}_README.md
    
    - name: check for changes and git push
      continue-on-error: true
      run: |
        cd git
        git branch --show-current
        if [[ `git status -s` ]]; then
          echo "CHANGED"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${GITHUB_RUN_NUMBER}_README.md
          git add README.md
          git commit -m "Add changes" -a
          git push
        else
          echo "NO CHANGED"
        fi
    - uses: actions/upload-artifact@v2
      with:
        name: relations
        path: ./relations
    - name: B2 Upload
      uses: wilsonzlin/b2-upload-action@v1.0.1
      with:
        bucket: github-user
        uploadKey: users.tgz
        keyId: ${{ secrets.B2ID }}
        applicationKey: ${{ secrets.B2KEY }}
        file: ./users.tgz
        contentType: b2/x-auto
    - name: B2 Upload
      uses: wilsonzlin/b2-upload-action@v1.0.1
      with:
        bucket: github-user
        uploadKey: ${{ github.run_number }}_README.md
        keyId: ${{ secrets.B2ID }}
        applicationKey: ${{ secrets.B2KEY }}
        file: ./data/README.md
        contentType: b2/x-auto
