# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: user_V1

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
    inputs:
      timeout:
        description: 'timeout for minutes'     
        default: "1"
        
jobs:
  build:
    runs-on: ubuntu-latest
    #timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: dearbot/github-user
        token: ${{ secrets.PAT }}
        ref: main
        path: data
        lfs: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: python user_v4.py ${{ secrets.PAT }} ${{ github.event.inputs.timeout }}
      if: github.event_name == 'workflow_dispatch'
    - run: python user_v4.py ${{ secrets.PAT }} 120
      if: github.event_name == 'schedule'
    - name: move new files to job folder
      run: |
        for i in $(cat /tmp/users.txt); do if [ -f data/users/${i}.json ]; then mv data/users/${i}.json data/jobs/$GITHUB_RUN_NUMBER/${i}.json; fi; done
    - run: python user_v4.py
    - run: cat data/README.md
    - name: check for changes and git push
      continue-on-error: true
      run: |
        cd data
        git branch --show-current
        if [[ `git status -s` ]]; then
          echo "CHANGED"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add relations/relations.txt
          git add jobs/$GITHUB_RUN_NUMBER
          git add README.md
          git commit -m "Add changes" -a
          git push
        else
          echo "NO CHANGED"
        fi
